backend:
  name: git-gateway
  publish_mode: editorial_workflow
  branch: master # Branch to update (optional; defaults to master)

media_folder: "themes/ync/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: "Blurb", name: blurb, widget: object, fields: [
      {label: "Heading", name: "heading", widget: string},
      {label: "Text", name: "text", widget: "text"}]}
      - {label: "Intro", name: intro, widget: object, fields: [
      {label: "Heading", name: "heading", widget: string},
      {label: "Text", name: "text", widget: "text"}]}
      - {label: "Products", name: products, widget: list, fields: [
      {label: "Image", name: "image", widget: "image"},
      {label: "Text", name: "text", widget: "text"}]}
      - {label: "Values", name: "values", widget: "object", fields: [
      {label: "Heading", name: "heading", widget: string},
      {label: "Text", name: "text", widget: "text"}]}

  - name: "projects" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Project Background", name: project_bg, widget: string}
      - {label: "Project Color", name: project_color, widget: string}
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: markdown}
      - {label: Image, name: image, widget: image}
      - {label: "Services Provided", name: services_provided, widget: select, multiple: true,
         options: ["UI/UX Design", "Mobile App Design", "Graphic Design", "Illustration", "Brand Identity", "Videography", "Photography", "Motion Graphics"], default: ["UI/UX Design"]}
      - {label: Website, name: website, widget: string, required: false}
      - {label: "Case Study", name: case_study, widget: string, required: false}
      - {label: "Description", name: block, widget: list, fields: [
        {label: "Title", name: "text", widget: string},
        {label: "Content", name: "content", widget: markdown}]}
      - {label: "Image List", name: image_list, widget: list, fields: [
        {label: "Image", name: "image", widget: image}]}

  - name: "home-section"
    label: "Homepage"
    files:
      - file: "data/home/herobanner.json"
        label: "Banner"
        name: "banner"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: markdown}
      - file: "data/home/projects.json"
        label: "Projects"
        name: "projects"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: CTA, name: cta, widget: string}
          - {label: URL, name: url, widget: string}
      - file: "data/home/whatwedo.json"
        label: "What we do"
        name: "what_we_do"
        fields:
          - {label: "Title", name: title, widget: string}
          - {label: "Subtitle", name: subtitle, widget: markdown}
          - {label: "Features", name: feature, widget: list, fields: [
            {label: "Title", name: "text", widget: string},
            {label: "Icon", name: "icon", widget: image}]}
  - name: "menu"
    label: "Menu"
    files:
      - file: "data/menu/menu.json"
        label: "Menu"
        name: "menu"
        fields:
          - {label: "Logo", name: "logo", widget: image}
          - {label: "Menu", name: menu, widget: list, fields: [
            {label: "Text", name: "text", widget: string},
            {label: "Link", name: "link", widget: string},
            {label: "Custom class", name: "class", widget: string}]}
  - name: "contact"
    label: "Contact"
    files:
      - file: "data/contact/contact.json"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: string}
          - {label: "Subtitle", name: "subtitle", widget: markdown}
          - {label: "Location", name: "location_text", widget: string}
          - {label: "Location Icon", name: "location_icon", widget: image}
          - {label: "Phone Number", name: "phone_number", widget: string}
          - {label: "Phone Icon", name: "phone_icon", widget: image}
          - {label: "Email", name: "email", widget: string}
          - {label: "Email Icon", name: "email_icon", widget: image}
