backend:
  name: git-gateway
  publish_mode: editorial_workflow
  branch: master # Branch to update (optional; defaults to master)

media_folder: "" # Folder where user uploaded files should go
public_folder: ""

collections:

  - name: "posts" # Used in routes, e.g., /admin/collections/blog

    label: "Post" # Used in the UI

    folder: "content/post" # The path to the folder where the documents are stored

    create: true # Allow users to create new documents in this collection

    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"

      - label: "Draft"
        name: "draft"
        required: false
        widget: "boolean"
        default: true

      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"

      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"

      - label: "Keywords"
        name: "keywords"
        required: false
        widget: "list"

      - label: "Auto Thumbnail Image"
        name: "autoThumbnailImage"
        required: false
        widget: "boolean"
        default: true

      - label: "Thumbnail Image Position"
        name: "thumbnailImagePosition"
        required: false
        widget: "select"
        options: ["left", "top", "right"]

      - label: "Thumbnail Image"
        name: "thumbnailImage"
        required: false
        widget: "image"

      - label: "Cover Image"
        name: "coverImage"
        required: false
        widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
